[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"


[[redirects]]
  from = "/comments/*"
  to = "http://jamstack-comments.netlify.com/*"
  status = 200

[[redirects]]
  from = "/twavatar/*"
  to = "https://twavatar.netlify.com/*"
  status = 200
